# Base configs
baseurl: "https://xinyiprincess.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "My Lovely Princess"
subtitle: "Happy Birthday"
author: "Lisheng"
header:
 title: "Memory"
 subtitle: "by lisheng"
footer:
 name: "Happy Birthday"
 bio: "It's a gift from Lisheng, and it's another self-made gift! \n I'm so lucky to know you in your last year. \n Hope you have another excellent year adventure! (Of course with me) Love you all the time!"
web_design: "AJ"
